### ISSUE TITLE
Formatting for this page is broken, at least the 'de-de' language version

### ISSUE THREAD

**Issue by chlandsi** [MicrosoftDocs/WSL.de-DE#8]
The block after "To install the Linux kernel update package:" is formatted as code and shows literal markup.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Aktualisieren des WSL2-Linux-Kernels](https://docs.microsoft.com/de-de/windows/wsl/wsl2-kernel)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL.de-DE/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @chlandsi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @<contributor's GITHUB name>, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/WSL/issues/596

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
