### ISSUE TITLE
--verbose is not an option anymore

### ISSUE THREAD

**Issue by ajoe** [MicrosoftDocs/WSL.de-DE#9]
using "wsl --list --verbose" doesn't work with Microsoft Windows [Version 10.0.18363.815]
"-v" or "--verbose" is not a valid option.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Installieren von WSL 2](https://docs.microsoft.com/de-de/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL.de-DE/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @ajoe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @ajoe, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/WSL/issues/673. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
